### PR TITLE
Feature/issue 01 connect and clone repo

### PR DESCRIPTION
**Pull request by olpie101**
Connect to unicore.distribute instance, clone data an store locally.

### CODE REVIEW

**Comment by olpie101** [comment]
Image of the time

**Comment by olpie101** [comment]
Pull request almost done :smile:. Here are some screenshots:
Image of the screen full actionbar
Image of screen collapsed actionbar
Nothing is complete without an animated gif :fireworks: 
Animated flow

**Comment by olpie101** [comment]
Pulll request done. All tests pass. :smile: 

@smn ready for a look over.

**Comment by smn** [comment]
whoa!

**Comment by smn** [comment]
This made my day! Will review in the morning.

**Comment by smn** [comment]
:+1: simply because the size of the pull-request, my limited ability to review Kotlin code and me being about this progressing! I'm hoping we can spend more time together on this so we can learn :)

yay

**Comment by olpie101** [comment]
Sure :smile:

**Pull request merged**
